version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.28
    - 14.14.30
    - 14.14.32
    - 14.14.34
    - 14.14.35
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: "@storybook/addon-essentials"
    versions:
    - 6.1.15
    - 6.1.17
    - 6.1.18
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.3
    - 6.2.4
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: "@babel/core"
    versions:
    - 7.12.13
    - 7.13.1
    - 7.13.10
    - 7.13.14
    - 7.13.15
  - dependency-name: styled-icons
    versions:
    - 10.28.0
    - 10.31.0
    - 10.32.0
  - dependency-name: next
    versions:
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.1
    - 10.1.2
    - 10.1.3
  - dependency-name: faker
    versions:
    - 5.3.1
    - 5.4.0
    - 5.5.1
    - 5.5.2
  - dependency-name: "@types/jest"
    versions:
    - 26.0.22
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
  - dependency-name: eslint-plugin-react
    versions:
    - 7.23.1
  - dependency-name: ts-jest
    versions:
    - 26.5.4
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.3
  - dependency-name: git-commit-msg-linter
    versions:
    - 3.0.3
    - 3.0.4
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.16.1
    - 4.17.0
    - 4.18.0
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.22.0
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.8
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.15.0
    - 4.15.1
    - 4.16.1
  - dependency-name: husky
    versions:
    - 5.1.1
    - 5.1.2
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.15
    - 6.1.20
  - dependency-name: core-js
    versions:
    - 3.9.0
